#!/usr/bin/env python3
"""
generate_thx_defaults.py -- produce AP_TiltHexa_SeedDefaults.h from the seed YAML.

Usage:
    python3 generate_thx_defaults.py [--yaml config/tilt_hexa_30kg_seed.yaml]
                                     [--out ../libraries/AP_TiltHexa/AP_TiltHexa_SeedDefaults.h]

The generated header contains only #define THX_SEED_* constants.
It is committed so that the C++ build does not depend on the YAML at compile time.
The test test_seed_header_fresh.py regenerates to a temp file and fails if the
committed header differs.
"""

import argparse
import math
import os
import sys
import yaml  # PyYAML


def load_yaml(path: str) -> dict:
    with open(path, "r") as f:
        return yaml.safe_load(f)


def generate_header(cfg: dict) -> str:
    lines = []
    lines.append("// AP_TiltHexa_SeedDefaults.h")
    lines.append("// REFERENCE_SEED_NOT_MEASURED -- generated from tilt_hexa_30kg_seed.yaml, do not edit")
    lines.append("//")
    lines.append("// Generated by: Tools/tilt_hexa_30kg/config/generate_thx_defaults.py")
    lines.append("")
    lines.append("#pragma once")
    lines.append("")
    lines.append("// ============================================================")
    lines.append("// Mass")
    lines.append("#define THX_SEED_MASS_KG  {}".format(cfg["mass"]["m_kg"]))
    lines.append("")
    lines.append("// ============================================================")
    lines.append("// Inertia (kg*m^2)")
    for key in ["Jxx", "Jyy", "Jzz", "Jxy", "Jxz", "Jyz"]:
        lines.append("#define THX_SEED_{}  {}".format(key.upper(), cfg["inertia"][key]))
    lines.append("")
    lines.append("// ============================================================")
    lines.append("// Geometry")
    geo = cfg["geometry"]
    lines.append("#define THX_SEED_WING_SPAN_M        {}".format(geo["wing_span_m"]))
    lines.append("#define THX_SEED_WING_AREA_M2       {}".format(geo["wing_area_m2"]))
    lines.append("#define THX_SEED_MAC_M              {}".format(geo["mean_aero_chord_m"]))
    lines.append("#define THX_SEED_ARM_RADIUS_M       {}".format(geo["arm_radius_m"]))
    lines.append("#define THX_SEED_ROTOR_Z_M          {}".format(geo["rotor_z_m"]))
    lines.append("#define THX_SEED_TAIL_ARM_M         {}".format(geo["tail_arm_m"]))
    lines.append("#define THX_SEED_VTAIL_DIHEDRAL_DEG {}".format(geo["vtail_dihedral_deg"]))
    lines.append("#define THX_SEED_VTAIL_AREA_M2      {}".format(geo["vtail_area_m2"]))
    lines.append("")
    lines.append("// ============================================================")
    lines.append("// Propulsion")
    prop = cfg["propulsion"]
    lines.append("#define THX_SEED_T_MAX_N            {}".format(prop["max_static_thrust_N"]))
    lines.append("#define THX_SEED_KAPPA_Q            {}".format(prop["kappa_Q"]))
    lines.append("#define THX_SEED_THRUST_EXPO        {}".format(prop["thrust_curve_expo"]))
    lines.append("#define THX_SEED_TAU_T_S            {}".format(prop["motor_time_constant_s"]))
    lines.append("")
    lines.append("// ============================================================")
    lines.append("// Tilt actuator")
    tilt = cfg["tilt"]
    lines.append("#define THX_SEED_TILT_MIN_DEG       {}".format(tilt["min_deg"]))
    lines.append("#define THX_SEED_TILT_MAX_DEG       {}".format(tilt["max_deg"]))
    lines.append("#define THX_SEED_TILT_RATE_DEG_S    {}".format(tilt["max_rate_deg_s"]))
    lines.append("#define THX_SEED_TAU_BETA_S         {}".format(tilt["time_constant_s"]))
    lines.append("#define THX_SEED_THR_OFF_N          {}".format(tilt["low_thrust_off_N"]))
    lines.append("#define THX_SEED_THR_ON_N           {}".format(tilt["low_thrust_on_N"]))
    lines.append("")
    lines.append("// ============================================================")
    lines.append("// Surface actuator")
    surf = cfg["surfaces"]
    lines.append("#define THX_SEED_AIL_MAX_DEG        {}".format(surf["aileron_left_max_deg"]))
    lines.append("#define THX_SEED_RV_MAX_DEG         {}".format(surf["ruddervator_left_max_deg"]))
    lines.append("#define THX_SEED_SURF_RATE_DEG_S    {}".format(surf["max_rate_deg_s"]))
    lines.append("#define THX_SEED_TAU_SURF_S         {}".format(surf["time_constant_s"]))
    lines.append("")
    lines.append("// ============================================================")
    lines.append("// Flight")
    fl = cfg["flight"]
    lines.append("#define THX_SEED_RHO_KG_M3          {}".format(fl["rho_kg_m3"]))
    lines.append("")
    lines.append("// ============================================================")
    lines.append("// Aero neutral coefficients")
    aero = cfg["aero"]
    lines.append("#define THX_SEED_CL0                {}".format(aero["CL0"]))
    lines.append("#define THX_SEED_CL_ALPHA           {}".format(aero["CL_alpha_per_rad"]))
    lines.append("#define THX_SEED_CL_MAX             {}".format(aero["CL_max"]))
    lines.append("#define THX_SEED_ALPHA_STALL_DEG    {}".format(aero["alpha_stall_deg"]))
    lines.append("#define THX_SEED_CD0                {}".format(aero["CD0"]))
    lines.append("#define THX_SEED_OSWALD_E           {}".format(aero["oswald_e"]))
    lines.append("#define THX_SEED_CM0                {}".format(aero["Cm0"]))
    lines.append("#define THX_SEED_CM_ALPHA           {}".format(aero["Cm_alpha_per_rad"]))
    lines.append("#define THX_SEED_CY_BETA            {}".format(aero["CY_beta_per_rad"]))
    lines.append("#define THX_SEED_CL_BETA            {}".format(aero["Cl_beta_per_rad"]))
    lines.append("#define THX_SEED_CN_BETA            {}".format(aero["Cn_beta_per_rad"]))
    lines.append("#define THX_SEED_CLP                 {}".format(aero["Clp_per_rad"]))
    lines.append("#define THX_SEED_CMQ                 {}".format(aero["Cmq_per_rad"]))
    lines.append("#define THX_SEED_CNR                 {}".format(aero["Cnr_per_rad"]))
    lines.append("")
    lines.append("// ============================================================")
    lines.append("// Surface derivatives (Section 0.2 convention)")
    asurf = aero["surfaces"]
    lines.append("#define THX_SEED_CL_DA              {}".format(asurf["CL_da"]))
    lines.append("#define THX_SEED_CL_DA_ROLL         {}".format(asurf["Cl_da"]))
    lines.append("#define THX_SEED_CM_DA              {}".format(asurf["Cm_da"]))
    lines.append("#define THX_SEED_CN_DA              {}".format(asurf["Cn_da"]))
    lines.append("#define THX_SEED_CL_DRV             {}".format(asurf["CL_drv"]))
    lines.append("#define THX_SEED_CL_DRV_ROLL        {}".format(asurf["Cl_drv"]))
    lines.append("#define THX_SEED_CM_DRV             {}".format(asurf["Cm_drv"]))
    lines.append("#define THX_SEED_CN_DRV             {}".format(asurf["Cn_drv"]))
    lines.append("")
    lines.append("// ============================================================")
    lines.append("// Allocation")
    alloc = cfg["allocation"]
    ws = alloc["Ws"]
    lines.append("#define THX_SEED_WS_FX              {}".format(ws[0]))
    lines.append("#define THX_SEED_WS_FZ              {}".format(ws[1]))
    lines.append("#define THX_SEED_WS_MX              {}".format(ws[2]))
    lines.append("#define THX_SEED_WS_MY              {}".format(ws[3]))
    lines.append("#define THX_SEED_WS_MZ              {}".format(ws[4]))
    lines.append("#define THX_SEED_W_DELTA_U          {}".format(alloc["Wdelta"]))
    lines.append("#define THX_SEED_W_U                {}".format(alloc["Wu"]))
    lines.append("#define THX_SEED_POLY_N             {}".format(alloc["polygon_facets"]))
    lines.append("")
    lines.append("// ============================================================")
    lines.append("// Filter cutoff frequencies (Hz)")
    ctrl = cfg["control"]
    lines.append("#define THX_SEED_ACCEL_FILT_HZ      {}".format(ctrl["accel_filter_hz"]))
    lines.append("#define THX_SEED_GYRO_DERIV_FILT_HZ {}".format(ctrl["gyro_derivative_filter_hz"]))
    lines.append("#define THX_SEED_ACT_FILT_HZ        {}".format(ctrl["actuator_filter_hz"]))
    lines.append("")
    lines.append("// ============================================================")
    lines.append("// PWM maps (microseconds)")
    pwm = cfg["pwm_maps"]
    lines.append("#define THX_SEED_MOTOR_PWM_MIN_US   {}".format(pwm["motor_min_us"]))
    lines.append("#define THX_SEED_MOTOR_PWM_MAX_US   {}".format(pwm["motor_max_us"]))
    lines.append("#define THX_SEED_TILT_PWM_MIN_US    {}".format(pwm["tilt_min_us"]))
    lines.append("#define THX_SEED_TILT_PWM_MAX_US    {}".format(pwm["tilt_max_us"]))
    lines.append("#define THX_SEED_SURF_PWM_MIN_US    {}".format(pwm["surface_min_us"]))
    lines.append("#define THX_SEED_SURF_PWM_TRIM_US   {}".format(pwm["surface_trim_us"]))
    lines.append("#define THX_SEED_SURF_PWM_MAX_US    {}".format(pwm["surface_max_us"]))
    lines.append("")
    lines.append("// ============================================================")
    lines.append("// Nondimensionalisation")
    nd = cfg["nondim"]
    lines.append("#define THX_SEED_D_U_T_N            {}".format(nd["D_u_T_N"]))
    lines.append("#define THX_SEED_D_U_DELTA_RAD      {}".format(nd["D_u_delta_rad"]))
    lines.append("#define THX_SEED_D_W_F_N            {}".format(nd["D_w_F_N"]))
    lines.append("#define THX_SEED_D_W_M_NM           {}".format(nd["D_w_M_Nm"]))

    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Generate THX seed defaults header")
    parser.add_argument("--yaml", default=None,
                        help="Path to seed YAML")
    parser.add_argument("--out", default=None,
                        help="Output header path")
    args = parser.parse_args()

    script_dir = os.path.dirname(os.path.abspath(__file__))
    yaml_path = args.yaml or os.path.join(script_dir, "tilt_hexa_30kg_seed.yaml")
    out_path = args.out or os.path.join(
        script_dir, "..", "..", "..", "libraries", "AP_TiltHexa", "AP_TiltHexa_SeedDefaults.h"
    )
    out_path = os.path.normpath(out_path)

    cfg = load_yaml(yaml_path)
    header_text = generate_header(cfg)

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write(header_text)

    print(f"Generated {out_path} from {yaml_path}")


if __name__ == "__main__":
    main()
