// AP_TiltHexa_SeedDefaults.h
// REFERENCE_SEED_NOT_MEASURED -- generated from tilt_hexa_30kg_seed.yaml, do not edit
//
// Generated by: Tools/tilt_hexa_30kg/config/generate_thx_defaults.py

#pragma once

// ============================================================
// Mass
#define THX_SEED_MASS_KG  30.0

// ============================================================
// Inertia (kg*m^2)
#define THX_SEED_JXX  4.267
#define THX_SEED_JYY  6.635
#define THX_SEED_JZZ  9.577
#define THX_SEED_JXY  0.0
#define THX_SEED_JXZ  0.0
#define THX_SEED_JYZ  0.0

// ============================================================
// Geometry
#define THX_SEED_WING_SPAN_M        3.5
#define THX_SEED_WING_AREA_M2       1.26
#define THX_SEED_MAC_M              0.36
#define THX_SEED_ARM_RADIUS_M       0.8
#define THX_SEED_ROTOR_Z_M          -0.15
#define THX_SEED_TAIL_ARM_M         1.2
#define THX_SEED_VTAIL_DIHEDRAL_DEG 35.0
#define THX_SEED_VTAIL_AREA_M2      0.18

// ============================================================
// Propulsion
#define THX_SEED_T_MAX_N            95.0
#define THX_SEED_KAPPA_Q            0.034
#define THX_SEED_THRUST_EXPO        0.65
#define THX_SEED_TAU_T_S            0.08

// ============================================================
// Tilt actuator
#define THX_SEED_TILT_MIN_DEG       -10.0
#define THX_SEED_TILT_MAX_DEG       90.0
#define THX_SEED_TILT_RATE_DEG_S    60.0
#define THX_SEED_TAU_BETA_S         0.15
#define THX_SEED_THR_OFF_N          5.0
#define THX_SEED_THR_ON_N           8.0

// ============================================================
// Surface actuator
#define THX_SEED_AIL_MAX_DEG        20.0
#define THX_SEED_RV_MAX_DEG         25.0
#define THX_SEED_SURF_RATE_DEG_S    120.0
#define THX_SEED_TAU_SURF_S         0.05

// ============================================================
// Flight
#define THX_SEED_RHO_KG_M3          1.225

// ============================================================
// Aero neutral coefficients
#define THX_SEED_CL0                0.2
#define THX_SEED_CL_ALPHA           4.8
#define THX_SEED_CL_MAX             1.45
#define THX_SEED_ALPHA_STALL_DEG    15.0
#define THX_SEED_CD0                0.04
#define THX_SEED_OSWALD_E           0.75
#define THX_SEED_CM0                0.02
#define THX_SEED_CM_ALPHA           -0.85
#define THX_SEED_CY_BETA            -0.45
#define THX_SEED_CL_BETA            -0.08
#define THX_SEED_CN_BETA            0.12
#define THX_SEED_CLP                 -0.45
#define THX_SEED_CMQ                 -12.0
#define THX_SEED_CNR                 -0.35

// ============================================================
// Surface derivatives (Section 0.2 convention)
#define THX_SEED_CL_DA              0.45
#define THX_SEED_CL_DA_ROLL         0.06
#define THX_SEED_CM_DA              0.0
#define THX_SEED_CN_DA              -0.004
#define THX_SEED_CL_DRV             0.3
#define THX_SEED_CL_DRV_ROLL        0.01
#define THX_SEED_CM_DRV             -0.55
#define THX_SEED_CN_DRV             0.035

// ============================================================
// Allocation
#define THX_SEED_WS_FX              2.0
#define THX_SEED_WS_FZ              5.0
#define THX_SEED_WS_MX              6.0
#define THX_SEED_WS_MY              6.0
#define THX_SEED_WS_MZ              4.0
#define THX_SEED_W_DELTA_U          20.0
#define THX_SEED_W_U                0.02
#define THX_SEED_POLY_N             12

// ============================================================
// Filter cutoff frequencies (Hz)
#define THX_SEED_ACCEL_FILT_HZ      12.0
#define THX_SEED_GYRO_DERIV_FILT_HZ 12.0
#define THX_SEED_ACT_FILT_HZ        12.0

// ============================================================
// PWM maps (microseconds)
#define THX_SEED_MOTOR_PWM_MIN_US   1000
#define THX_SEED_MOTOR_PWM_MAX_US   2000
#define THX_SEED_TILT_PWM_MIN_US    1000
#define THX_SEED_TILT_PWM_MAX_US    2000
#define THX_SEED_SURF_PWM_MIN_US    1000
#define THX_SEED_SURF_PWM_TRIM_US   1500
#define THX_SEED_SURF_PWM_MAX_US    2000

// ============================================================
// Nondimensionalisation
#define THX_SEED_D_U_T_N            95.0
#define THX_SEED_D_U_DELTA_RAD      0.349
#define THX_SEED_D_W_F_N            294.3
#define THX_SEED_D_W_M_NM           235.44
